/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author SENA
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        Clientes = new javax.swing.JButton();
        categorias = new javax.swing.JButton();
        productos = new javax.swing.JButton();
        ingredientes = new javax.swing.JButton();
        Empleado = new javax.swing.JButton();
        nombre_usuario = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        Coffee = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));

        Clientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clientes.setText("Clientes");
        Clientes.setBorderPainted(false);
        Clientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Clientes.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Clientes.setPreferredSize(new java.awt.Dimension(76, 23));
        Clientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });

        categorias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categorias.setText("categorias");
        categorias.setBorderPainted(false);
        categorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        categorias.setMargin(new java.awt.Insets(2, 2, 2, 2));
        categorias.setPreferredSize(new java.awt.Dimension(76, 23));
        categorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasActionPerformed(evt);
            }
        });

        productos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productos.setText("productos");
        productos.setBorderPainted(false);
        productos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        productos.setMargin(new java.awt.Insets(2, 2, 2, 2));
        productos.setPreferredSize(new java.awt.Dimension(76, 23));
        productos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosActionPerformed(evt);
            }
        });

        ingredientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ingredientes.setText("ingredientes");
        ingredientes.setBorderPainted(false);
        ingredientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ingredientes.setMargin(new java.awt.Insets(2, 2, 2, 2));
        ingredientes.setPreferredSize(new java.awt.Dimension(76, 23));
        ingredientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ingredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientesActionPerformed(evt);
            }
        });

        Empleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Empleado.setText("Empleado");
        Empleado.setBorderPainted(false);
        Empleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Empleado.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Empleado.setPreferredSize(new java.awt.Dimension(76, 23));
        Empleado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoActionPerformed(evt);
            }
        });

        nombre_usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombre_usuario.setText("Cerrar Sesion");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addComponent(nombre_usuario)
                        .addGap(28, 28, 28))))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(productos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(nombre_usuario)
                .addGap(41, 41, 41))
        );

        Clientes.putClientProperty(FlatClientProperties.STYLE,
            "focusedBackground:#fef0e1;focusedForeground:#ea6e00");
        categorias.putClientProperty(FlatClientProperties.STYLE,
            "focusedBackground:#fef0e1;focusedForeground:#ea6e00");
        productos.putClientProperty(FlatClientProperties.STYLE,
            "focusedBackground:#fef0e1;focusedForeground:#ea6e00");
        ingredientes.putClientProperty(FlatClientProperties.STYLE,
            "focusedBackground:#fef0e1;focusedForeground:#ea6e00");
        Empleado.putClientProperty(FlatClientProperties.STYLE,
            "focusedBackground:#fef0e1;focusedForeground:#ea6e00");

        contenedor.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 170, 820));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Coffee.setFont(new java.awt.Font("Segoe UI Semibold", 0, 40)); // NOI18N
        Coffee.setForeground(new java.awt.Color(243, 171, 82));
        Coffee.setText("Brew");
        header.add(Coffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 37));

        titulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 40)); // NOI18N
        titulo.setForeground(new java.awt.Color(109, 7, 5));
        titulo.setText("Lab");
        header.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 37));
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        contenedor.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 80));

        Contenido.setBackground(new java.awt.Color(246, 248, 247));
        Contenido.setLayout(new java.awt.CardLayout());
        contenedor.add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 1340, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
//        Contenido.add(new Productos(), "productos");
//        Vista.show(Contenido, "productos");
//        this.revalidate();
//        this.repaint();
    }//GEN-LAST:event_ClientesActionPerformed

    private void categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriasActionPerformed

    private void productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productosActionPerformed

    private void ingredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientesActionPerformed

    private void EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clientes;
    private javax.swing.JLabel Coffee;
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton Empleado;
    private javax.swing.JButton categorias;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel header;
    private javax.swing.JButton ingredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nombre_usuario;
    private javax.swing.JButton productos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
